#!/usr/bin/python3

import pyforms

from widgets import Menu
from base import Entity


# Execute the application
if __name__ == "__main__":
    import docx
    d = docx.Document()
    d.add_paragraph('a')
    d.save('aaa.docx')
    pyforms.start_app(Menu)
