#!/usr/bin/python3

import pyforms
from docx import Document
from docx.shared import Inches

from widgets import Menu
from base import Entity


# Execute the application
if __name__ == "__main__":
    pyforms.start_app(Menu)
